#!/usr/bin/env bash
#SBATCH --job-name="Romania6km"
#SBATCH --account=em05
#SBATCH --time="0:30:00"
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=128
#SBATCH --constraint=mc
#SBATCH --partition=debug
#SBATCH --hint=nomultithread

# OpenMP environment variables                                                 
# ----------------------------                                                 


export OMP_NUM_THREADS=1                                                       
export ICON_THREADS=1                                                          
export OMP_SCHEDULE=static,12                                                  
export OMP_DYNAMIC="false"                                                     
export OMP_STACKSIZE=200M                                                      
export FI_CXI_OPTIMIZED_MRS="false"

set -e -x
export ECCODES_DEFINITION_PATH=/capstor/scratch/cscs/msteiner/spack-c2sm-eiger/spack/opt/spack/linux-sles15-zen2/gcc-12.3/eccodes-2.25.0-yzq4f4flnxd7xhajhnlnfxfsex5j2bhm/share/eccodes/definitions

export LD_LIBRARY_PATH=/opt/cray/libfabric/1.15.2.0/lib64/:$LD_LIBRARY_PATH


# date=2019010100
date=2019100700

#basic folders
WORKDIR=${SCRATCH}/Romania6km
DATADIR=${WORKDIR}/input
#grids
GRIDDIR=${DATADIR}/grid/outer_grid/
EXTPARDIR=${GRIDDIR}
#IC/LBC
INIDIR=${DATADIR}/icbc_outer/merged/IC
LBCDIR=${DATADIR}/icbc_outer/merged/LBC
#ART/OEM
ARTDIR=${ICONDIR}/externals/art
OEMDIR=${DATADIR}/OEM
#run
# EXPDIR=${WORKDIR}/output_testsim
EXPDIR=${WORKDIR}/simulation_outer_domain
#ICON
ICONDIR=${SCRATCH}/icon-nwp


mkdir -p $EXPDIR
cd ${EXPDIR}



# reduced radiation grid file
ln -sf ${GRIDDIR}/parent_grid.nc .
# limited area grid
ln -sf ${GRIDDIR}/dyn_grid.nc .
# lateral boundary grid
ln -sf ${GRIDDIR}/lateral_boundary.grid.nc .
# external parameter
ln -sf ${EXTPARDIR}/extpar_file.nc .
# initial and boundary data
ln -sf ${INIDIR}/era5_${date}.nc era5_init.nc
# files needed for radiation
ln -sf ${ICONDIR}/data/ECHAM6_CldOptProps.nc rrtm_cldopt.nc
ln -sf ${ICONDIR}/data/rrtmg_lw.nc .
# Dictionary for the mapping: DWD GRIB2 names <-> ICON internal names
ln -s ${ICONDIR}/run/ana_varnames_map_file.txt map_file.ana
ln -s ${GRIDDIR}/map_file.latbc .


# ----------------------------------------------------------------------------
# Link radiation input files
# ----------------------------------------------------------------------------
ln -sf ${ARTDIR}/runctrl_examples/photo_ctrl/* .
ln -sf ${ARTDIR}/runctrl_examples/init_ctrl/* .

# ----------------------------------------------------------------------------
# create ICON master namelist
# ----------------------------------------------------------------------------

cat > icon_master.namelist << EOF
! master_nml: ----------------------------------------------------------------
&master_nml
 lrestart                   =                     .FALSE.        ! .TRUE.=current experiment is resumed
/

&master_time_control_nml
    restarttimeintval = 'PT24H'
/

! master_model_nml: repeated for each model ----------------------------------
&master_model_nml
 model_type                  =                          1         ! identifies which component to run (atmosphere,ocean,...)
 model_name                  =                      "ATMO"        ! character string for naming this component.
 model_namelist_filename     =              "NAMELIST_NWP"        ! file name containing the model namelists
 model_min_rank              =                          1         ! start MPI rank for this model
 model_max_rank              =                      65536         ! end MPI rank for this model
 model_inc_rank              =                          1         ! stride of MPI ranks
/

! time_nml: specification of date and time------------------------------------
&time_nml
 ! dt_restart                  =      604800
 ini_datetime_string         =      "2019-10-07T00:00:00Z"        ! initial date and time of the simulation
 end_datetime_string         =      "2020-01-01T00:00:00Z"        ! end date and time of the simulation
/
EOF

# ----------------------------------------------------------------------
# model namelists
# ----------------------------------------------------------------------

cat > NAMELIST_NWP << EOF
! parallel_nml: MPI parallelization -------------------------------------------
&parallel_nml
 nproma                      =                         16
 p_test_run                  =                     .FALSE.        ! .TRUE. means verification run for MPI parallelization
 num_io_procs                =                          3         ! number of I/O processors
 num_restart_procs           =                          1         ! number of restart processors
 num_prefetch_proc           =                          1         ! number of processors for LBC prefetching
 iorder_sendrecv             =                          3         ! sequence of MPI send/receive calls
/

! comin_nml: comin tool ---------------------------------------------
&comin_nml                                                                  
plugin_list(1)%name          = "comin_plugin"
plugin_list(1)%plugin_library = "/capstor/scratch/cscs/zhug/icon-nwp/externals/comin/build/plugins/python_adapter/libpython_adapter.so"
plugin_list(1)%options        = "/capstor/scratch/cscs/zhug/Romania6km/python-zeno/CH4_tracker.py"

/

! run_nml: general switches ---------------------------------------------------
&run_nml
 ltestcase                   =                     .FALSE.        ! real case run
 num_lev                     =                         90         ! number of full levels (atm.) for each domain
 lvert_nest                  =                     .FALSE.        ! no vertical nesting
 dtime                       =                         60         ! timestep in seconds
 ldynamics                   =                      .TRUE.        ! compute adiabatic dynamic tendencies
 ltransport                  =                      .TRUE.        ! compute large-scale tracer transport
 ntracer                     =                          0         ! number of advected tracers
 iforcing                    =                          3         ! forcing of dynamics and transport by parameterized processes
 msg_level                   =                          10        ! detailed report during integration
 ltimer                      =                      .TRUE.        ! timer for monitoring the runtime of specific routines
 timers_level                =                         10         ! performance timer granularity
 check_uuid_gracefully       =                      .TRUE.        ! give only warnings for non-matching uuids
 output                      =                        "nml"       ! main switch for enabling/disabling components of the model output
 lart                        =                      .True.        ! main switch for ART
 debug_check_level           =                         10
/

! art_nml: Aerosols and Reactive Trace gases extension-------------------------------------------------
&art_nml
 lart_chem                  =                        .TRUE.       ! enables chemistry
 lart_pntSrc                =                       .FALSE.       ! enables point sources
 lart_aerosol               =                       .FALSE.       ! main switch for the treatment of atmospheric aerosol
 lart_chemtracer            =                        .TRUE.       ! main switch for the treatment of chemical tracer
 lart_diag_out              =                        .TRUE.       ! If this switch is set to .TRUE., diagnostic
                                                                  ! ... output elds are available. Set it to
                                                                  ! ... .FALSE. when facing memory problems.
 iart_init_gas              =                            4
 cart_cheminit_file         =               "era5_init.nc"
 cart_cheminit_type         =                       'EMAC'
 cart_cheminit_coord        =               "era5_init.nc"
 iart_seasalt               =                            0        ! enable seasalt
 cart_chemtracer_xml        =  '${DATADIR}/XML/tracers_fwd.xml'
 cart_input_folder          =  '/capstor/scratch/cscs/nponomar/ICON_ctdas_msteiner/ART_case8'
/

! oem_nml: online emission module ---------------------------------------------
&oemctrl_nml                                                                   
 gridded_emissions_nc        =   '${OEMDIR}/final_emissions_outer.nc'
 vertical_profile_nc         =   '${OEMDIR}/vertical_profiles_mod.nc'
 hour_of_day_nc              =   '${OEMDIR}/hourofday.nc'
 day_of_week_nc              =   '${OEMDIR}/dayofweek.nc'
 month_of_year_nc            =   '${OEMDIR}/monthofyear.nc'
/


! diffusion_nml: horizontal (numerical) diffusion ----------------------------
&diffusion_nml
 lhdiff_vn                   =                      .TRUE.        ! diffusion on the horizontal wind field
 lhdiff_temp                 =                      .TRUE.        ! diffusion on the temperature field
 lhdiff_w                    =                      .TRUE.        ! diffusion on the vertical wind field
 hdiff_order                 =                          5         ! order of nabla operator for diffusion
 itype_vn_diffu              =                          1         ! reconstruction method used for Smagorinsky diffusion
 itype_t_diffu               =                          2         ! discretization of temperature diffusion
 hdiff_efdt_ratio            =                         24.0       ! ratio of e-folding time to time step 
 hdiff_smag_fac              =                          0.025     ! scaling factor for Smagorinsky diffusion
/

! dynamics_nml: dynamical core -----------------------------------------------
&dynamics_nml
 iequations                  =                          3         ! type of equations and prognostic variables
 divavg_cntrwgt              =                          0.50      ! weight of central cell for divergence averaging
 lcoriolis                   =                      .TRUE.        ! Coriolis force
/

! extpar_nml: external data --------------------------------------------------
&extpar_nml
 itopo                       =                          1         ! topography (0:analytical)
 extpar_filename             =            'extpar_file.nc'
 n_iter_smooth_topo          =                          5         ! iterations of topography smoother
 hgtdiff_max_smooth_topo     =                        500.        ! see Namelist doc
 heightdiff_threshold        =                        900.
 itype_vegetation_cycle      =                          3         ! gdm orig. 1 tweaks the annual cycle of LAI
 itype_lwemiss               =                          2
/

! initicon_nml: specify read-in of initial state ------------------------------
&initicon_nml
 init_mode                   =                         2          ! 7: start from DWD fg with subsequent vertical remapping 
 lread_ana                   =                    .FALSE.         ! no analysis data will be read
 ifs2icon_filename	         =             "era5_init.nc"
 ana_varnames_map_file       =             "map_file.ana"
 ltile_coldstart             =                      .TRUE.        ! coldstart for surface tiles
 ltile_init                  =                     .FALSE.        ! set it to .TRUE. if FG data originate from run without tiles
/

! grid_nml: horizontal grid --------------------------------------------------
&grid_nml
 dynamics_grid_filename      =              "dyn_grid.nc"
 radiation_grid_filename     =           "parent_grid.nc"
 dynamics_parent_grid_id     =                          0         ! array of the indexes of the parent grid filenames
 lredgrid_phys               =                      .TRUE.        ! .true.=radiation is calculated on a reduced grid
 lfeedback                   =                      .TRUE.        ! specifies if feedback to parent grid is performed
 l_limited_area              =                      .TRUE.        ! .TRUE. performs limited area run
 ifeedback_type              =                          2         ! feedback type (incremental/relaxation-based)
 start_time                  =                          0.        ! Time when a nested domain starts to be active [s]
/

! gridref_nml: grid refinement settings --------------------------------------
&gridref_nml
 denom_diffu_v               =                        150.        ! denominator for lateral boundary diffusion of velocity
/

! interpol_nml: settings for internal interpolation methods ------------------
&interpol_nml
 nudge_zone_width            =                         42         ! width of lateral boundary nudging zone
 support_baryctr_intp        =                     .FALSE.        ! barycentric interpolation support for output
 nudge_max_coeff             =                       0.069
 nudge_efold_width           =                        2.0
/


! io_nml: general switches for model I/O -------------------------------------
&io_nml
 itype_pres_msl              =                          5         ! method for computation of mean sea level pressure
 itype_rh                    =                          1         ! method for computation of relative humidity
 lmask_boundary              =                      .TRUE.        ! mask out interpolation zone in output
/

! limarea_nml: settings for limited area mode ---------------------------------
&limarea_nml
 itype_latbc                 =                          1         ! 1: time-dependent lateral boundary conditions
 dtime_latbc                 =                        10800 !3600        ! time difference between 2 consecutive boundary data
 nlev_latbc                  =                         60         ! Number of vertical levels in boundary data
 latbc_boundary_grid         =   "lateral_boundary.grid.nc"
 latbc_path                 =                 "${LBCDIR}"
 latbc_varnames_map_file     =             "map_file.latbc"
 latbc_filename             =     "era5_<y><m><d><h>_lbc.nc"
 init_latbc_from_fg          =                        .FALSE.      ! .TRUE.: take lbc for initial time from first guess
/

! lnd_nml: land scheme switches -----------------------------------------------
&lnd_nml
 ntiles                      =                          3         ! number of tiles
 nlev_snow                   =                          3         ! number of snow layers
 lmulti_snow                 =                      .FALSE.       ! .TRUE. for use of multi-layer snow model
 idiag_snowfrac              =                         20         ! type of snow-fraction diagnosis
 lsnowtile                   =                       .TRUE.       ! .TRUE.=consider snow-covered and snow-free separately
 itype_root                  =                          2         ! root density distribution
 itype_heatcond              =                          3         ! type of soil heat conductivity
 itype_lndtbl                =                          4         ! table for associating surface parameters
 itype_evsl                  =                          4         ! type of bare soil evaporation
 itype_root                  =                          2         ! root density distribution
 cwimax_ml                   =                      5.e-4         ! scaling parameter for max. interception storage
 c_soil                      =                       1.25         ! surface area density of the evaporative soil surface
 c_soil_urb                  =                        0.5         ! same for urban areas
 lseaice                     =                      .FALSE.        ! .TRUE. for use of sea-ice model
 llake                       =                      .TRUE.        ! .TRUE. for use of lake model
 itype_canopy                =                          2         ! Jan Peter scheme gdm orig. default 1
 itype_snowevap              =                          3         ! gdm: orig.: 2 Snow evap. in vegetated areas with add. variables for snow age and max. snow height
 itype_trvg                  =                          3         ! BATS scheme with add. prog. var. for integrated plant transpiration since sunrise
 sstice_mode                 =                          2         ! 2: SST is updated on a daily basis by climatological increments
/

! nonhydrostatic_nml: nonhydrostatic model -----------------------------------
&nonhydrostatic_nml
 iadv_rhotheta               =                          2         ! advection method for rho and rhotheta
 ivctype                     =                          2         ! type of vertical coordinate
 itime_scheme                =                          4         ! time integration scheme
 ndyn_substeps               =                          5         ! number of dynamics steps per fast-physics step
 exner_expol                 =                          0.333     ! temporal extrapolation of Exner function
 vwind_offctr                =                          0.2       ! off-centering in vertical wind solver
 damp_height                 =                      8000.0       ! height at which Rayleigh damping of vertical wind starts 12250.0 
 rayleigh_coeff              =                          5.0       ! Rayleigh damping coefficient
 divdamp_order               =                         24         ! order of divergence damping 
 divdamp_type                =                         32          ! type of divergence damping
 divdamp_fac                 =                          0.004     ! scaling factor for divergence damping
 igradp_method               =                          3         ! discretization of horizontal pressure gradient
 l_zdiffu_t                  =                      .TRUE.        ! specifies computation of Smagorinsky temperature diffusion
 thslp_zdiffu                =                          0.02      ! slope threshold (temperature diffusion)
 thhgtd_zdiffu               =                        125.0       ! threshold of height difference (temperature diffusion)
 htop_moist_proc             =                      22500.0       ! max. height for moist physics
 hbot_qvsubstep              =                      22500.0       ! height above which QV is advected with substepping scheme
/

! nwp_phy_nml: switches for the physics schemes ------------------------------
&nwp_phy_nml
 inwp_gscp                   =                          2         ! cloud microphysics and precipitation
 inwp_convection             =                          1         ! convection
 lshallowconv_only           =                      .FALSE.        ! only shallow convection
 lgrayzone_deepconv          =                      .FALSE.       !
 inwp_radiation              =                          1         ! radiation
 inwp_cldcover               =                          1         ! cloud cover scheme for radiation
 inwp_turb                   =                          1         ! vertical diffusion and transfer
 inwp_satad                  =                          1         ! saturation adjustment
 inwp_sso                    =                          1         ! subgrid scale orographic drag
 inwp_gwd                    =                          0         ! non-orographic gravity wave drag
 inwp_surface                =                          1         ! surface scheme
 latm_above_top              =                      .TRUE.        ! take into account atmosphere above model top for radiation computation
 ldetrain_conv_prec          =                      .TRUE.
 efdt_min_raylfric           =                       7200.        ! minimum e-folding time of Rayleigh friction
 itype_z0                    =                          2         ! type of roughness length data
 icapdcycl                   =                          3         ! apply CAPE modification to improve diurnalcycle over tropical land
 icpl_aero_conv              =                          1         ! coupling between autoconversion and Tegen aerosol climatology
 icpl_aero_gscp              =                          0         ! coupling between autoconversion and Tegen aerosol climatology
 mu_rain                     =                         0.5        ! shap parameter in gamma distribution for rain
 rain_n0_factor              =                         0.1        ! tuning factor for intercept parameter of raindrop size distr.
 dt_rad                      =                         600.       ! time step for radiation in s
 dt_conv                     =                          90.       ! time step for convection in s (domain specific)
 dt_sso                      =                          360.       ! time step for SSO parameterization
 dt_gwd                      =                          120.       ! time step for gravity wave drag parameterization
 lrtm_filename               =        'rrtmg_lw.nc'
 cldopt_filename             =        'rrtm_cldopt.nc'

/

! nwp_tuning_nml: additional tuning parameters ----------------------------------
&nwp_tuning_nml
 tune_v0snow                 =                        25
 tune_rcucov                 =                        0.075
 tune_rhebc_land             =                        0.825
 itune_albedo                =                          1         ! reduced albedo (w.r.t. MODIS data) over Sahara
 tune_gkwake                 =                        0.25
 tune_gfrcrit                =                        0.333
 tune_gkdrag                 =                        0.0
 tune_minsnowfrac            =                        0.3
 tune_box_liq                =                        0.04
 tune_box_liq_asy            =                        4
 tune_gust_factor            =                        7.0
 tune_zvz0i                  =                        1.25        ! new tuning since June 2018 ! gdm non in guenther
 tune_sgsclifac              =                        1.0         ! new tuning becoming operational in July 2019 ! gdm non in guenther
 icpl_turb_clc               =                        2
 max_calibfac_clcl           =                        2.0
/

! output_nml: specifies an output stream --------------------------------------
&output_nml
 filetype                    =                          4         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                         =                          1         ! write domain 1 only
 output_bounds               =        0., 1000000000., 3600.        ! start, end, increment
 steps_per_file              =                          1         ! number of steps per file
 mode                        =                          1         ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last                =                      .TRUE.
 output_filename             =                    'ICON-ART-UNSTR'
 filename_format             =    '<output_filename>_<datetime>'  ! file name base
 steps_per_file_inclfirst    =                    .FALSE.
 output_grid                 =                      .TRUE.
 remap                       =                          0         ! 1: remap to lat-lon grid
 !north_pole                 =                   -170.,40.        ! definition of north_pole for rotated lat-lon grid
 ml_varlist                  =  'group:PBL_VARS',
                                'group:ATMO_ML_VARS',
                                'group:precip_vars',
                                'group:land_vars',
                                'group:nh_prog_vars',
                                'z_mc', 'z_ifc', 'fis',
                                'geopot', 'qv', 'fr_land',
                                'c_t_lk', 'freshsnow', 'fr_seaice',
                                'h_ice', 'h_ml_lk', 'h_snow', 'qv_s',
                                'rho_snow', 't_bot_lk', 't_g', 't_ice',
                                't_mnw_lk', 't_snow', 't_wml_lk',
                                'w_i', 'w_snow', 'gz0', 'pres_sfc',
                                'clct','asob_s','aumfl_s','avmfl_s',
                                't_so', 'w_so', 'w_so_ice',
                                't_2m', 'smi','pres_ifc',
                                'topography_c',
                                'group:ART_CHEMISTRY',
/

! output_nml: specifies an output stream --------------------------------------
&output_nml
 filetype                    =                           4         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                         =                           1         ! write domain 1 only
 output_bounds               =         0., 10000000., 7200.        ! start, end, increment
 steps_per_file              =                           1         ! number of steps per file
 mode                        =                           1         ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last                =                       .TRUE.
 output_filename             =                'ICON-ART-STR'
 filename_format             = '<output_filename>_<datetime>'
 steps_per_file_inclfirst    =                      .FALSE.
 output_grid                 =                        .TRUE.
 remap                       =                            1         ! 1: remap to lat-lon grid
 !north_pole                 =                    -170.,40.       ! definition of north_pole for rotated lat-lon grid
 reg_lon_def                 =                19.6,0.07,30.0
 reg_lat_def                 =              43.27,0.07,48.57
 ml_varlist                  =         'group:nh_prog_vars',
                                       'group:ATMO_ML_VARS',
                                           'group:PBL_VARS',
                                            'z_mc', 'z_ifc','pres_ifc',
                                            'group:ART_CHEMISTRY',
/

! radiation_nml: radiation scheme ---------------------------------------------
&radiation_nml
 irad_o3                     =                          79         ! ozone climatology
 irad_aero                   =                          6         ! aerosols
 albedo_type                 =                          2         ! type of surface albedo
 vmr_co2                     =                    390.e-06
 vmr_ch4                     =                   1800.e-09
 vmr_n2o                     =                   322.0e-09
 vmr_o2                      =                     0.20946
 vmr_cfc11                   =                    240.e-12
 vmr_cfc12                   =                    532.e-12
 direct_albedo_water         =                           3
 albedo_whitecap             =                           1
/

! sleve_nml: vertical level specification -------------------------------------
&sleve_nml
 min_lay_thckn               =                         15.0       ! layer thickness of lowermost layer
 top_height                  =                      23000.0       ! height of model top
 stretch_fac                 =                          0.65      ! stretching factor to vary distribution of model levels
 decay_scale_1               =                       4000.0       ! decay scale of large-scale topography component
 decay_scale_2               =                       2500.0       ! decay scale of small-scale topography component
 decay_exp                   =                          1.2       ! exponent of decay function
 flat_height                 =                      16000.0       ! height above which the coordinate surfaces are flat
/

! transport_nml: tracer transport ---------------------------------------------
&transport_nml
 ivadv_tracer                =              3, 3, 3, 3, 3, 3      ! tracer specific method to compute vertical advection
 itype_hlimit                =              3, 4, 4, 4, 4, 4      ! type of limiter for horizontal transport
 ihadv_tracer                =             52, 2, 2, 2, 2, 2     ! tracer specific method to compute horizontal advection
 llsq_svd                    =                      .TRUE.        ! use SV decomposition for least squares design matrix
/

! turbdiff_nml: turbulent diffusion -------------------------------------------
&turbdiff_nml
 tkhmin                      =                          0.5      ! scaling factor for minimum vertical diffusion coefficient
 tkmmin                      =                          0.75      ! scaling factor for minimum vertical diffusion coefficient
 pat_len                     =                        750.0       ! effective length scale of thermal surface patterns
 tur_len                     =                        300.0       ! asymptotic maximal turbulent distance
! c_diff                      =                          0.2       ! length scale factor for vertical diffusion of TKE
 rat_sea                     =                          0.8       ! controls laminar resistance for sea surface
 ltkesso                     =                        .TRUE.      ! consider TKE-production by sub-grid SSO wakes
 frcsmot                     =                          0.2       ! these 2 switches together apply vertical smoothing of the TKE source terms
 imode_frcsmot               =                            2       ! in the tropics (only), which reduces the moist bias in the tropical lower troposphere
 itype_sher                  =                            2       ! type of shear forcing used in turbulence
 ltkeshs                     =                        .TRUE.      ! include correction term for coarse grids in hor. shear production term
 a_hshr                      =                          2.0       ! length scale factor for separated horizontal shear mode
 icldm_turb                  =                            2       ! mode of cloud water representation in turbulence
 ldiff_qi                    =                        .TRUE.
 q_crit                      =                          2.0       ! critical value for normalized supersaturation
 imode_tkesso                =                            2       ! mode of calculating th SSO source term for TKE production
 rlam_heat                   =                         10.0       ! gdm default seems to be 10 in code but 1 in Namelist_overview.pdf
 alpha1                      =                         0.125
/
EOF

# ----------------------------------------------------------------------
# run the model!
# ----------------------------------------------------------------------

# old
# cp -p /capstor/scratch/cscs/zhug/spack/opt/spack/linux-sles15-zen2/gcc-13.3.0/icon-icon-2024.10-dwd-3.0-7i2y5rw27gqzolhlv3lcmtfxelcpdysc/bin/icon icon.exe

cp /capstor/scratch/cscs/zhug/Romania6km/runscripts/flight*.csv /capstor/scratch/cscs/zhug/Romania6km/simulation_outer_domain/
cp /capstor/scratch/cscs/zhug/Romania6km/input/TROPOMI_SRON_20190101_20191231.nc /capstor/scratch/cscs/zhug/Romania6km/simulation_outer_domain/
# new 
cp -p  /capstor/scratch/cscs/zhug/spack/opt/spack/linux-sles15-zen2/gcc-13.3.0/icon-icon-2024.10-dwd-3.0-7i2y5rw27gqzolhlv3lcmtfxelcpdysc/bin/icon icon.exe

# Load the needed libraries
# spack load py-numpy
spack load py-scipy
spack load py-xarray
# spack load py-pandas
spack load py-mpi4py
spack load py-netcdf4

srun ./icon.exe
